### ISSUE TITLE
Cannot find function fillPage

### ISSUE THREAD

**Issue by homerhanumat** [rstudio/shinygadgets#3]
I have an Addin at a repo [here](https://github.com/homerhanumat/addinplots).  It works fine using a version of `shinygadgets` from a few days ago.  But using the current version I get this error:

```
>addinplots:::cloudplotAddin()
Error in tagList(fillPage(tags$div(class = "gadget-container", ...), title = title,  : 
  could not find function "fillPage"
```

**Comment by homerhanumat** [comment]
It seems the issue is that `fillPage()` was removed from `shinygadgets` and was to go into `shiny`, but it is not there yet (as of [this commit](https://github.com/rstudio/shiny/commit/72aaf3055a9bd4959677bb6a697c26872e3f6e58)).

**Comment by jcheng5** [comment]
Gah. Really sorry about that. FYI, a bunch of stuff is moving around--I'll try to keep master backwards compatible but you'll want to check in on the add-ins docs in a few days. We're now talking about moving away from the "shinygadgets" package name because it turns out this layout style may be useful for non-gadget scenarios too.

**Comment by jcheng5** [comment]
Should be fixed now if you reinstall shinygadgets.

**Comment by homerhanumat** [comment]
No worries, I'll keep an eye on the docs and commits.

**Comment by jjallaire** [comment]
We just revved the packages and docs so you can switch to the new scheme
now.

**Comment by jcheng5** [comment]
The scheme changed again, sorry. The docs have been updated to the new, new scheme.

**Comment by homerhanumat** [comment]
No problem.  I have updated my stuff to accord with the changes.

Addins will be a game-changer for my students!  Thanks for all of this work.
